dubbo:
  scan:
    base-packages: com.github.service
  protocols:
    dubbo:
      name: dubbo
      port: -1 #服务暴露的协议配置，其中子属性 name 为协议名称，port 为协议端口（ -1 表示自增端口，从 20880 开始）
  registry:
    address: spring-cloud://localhost
  consumer:
    timeout: 5000
    check: false
    retries: 0
  cloud:
    subscribed-services: