dubbo:
  scan:
    base-packages: com.github.service
  protocols:
    #配置两种协议，其中rest协议定义 8080 端口并使用 netty 作为应用服务器
    dubbo:
      name: dubbo
      port: -1
    rest:
      name: rest
      port: 8080
      server: netty
  registry:
    address: spring-cloud://localhost
  consumer:
    timeout: 5000
    check: false
    retries: 0
  cloud:
    subscribed-services: